# Generated by Django 2.2.6 on 2019-10-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('D', 'Doctor'), ('N', 'Nurse')], max_length=1),
        ),
    ]
