# Generated by Django 2.2.6 on 2019-10-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191028_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('D', 'Врач'), ('N', 'Медперсонал')], max_length=1),
        ),
    ]
