# Generated by Django 2.2.6 on 2019-10-24 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
