# Generated by Django 2.2.6 on 2019-10-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0006_auto_20191026_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
