# Generated by Django 2.2.6 on 2019-10-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0008_auto_20191026_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='room',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
