# Generated by Django 2.2.6 on 2019-10-28 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0011_auto_20191028_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
