# Generated by Django 2.2.6 on 2019-10-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0012_auto_20191028_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='owner',
        ),
    ]
