# Generated by Django 2.2.6 on 2019-10-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0013_remove_info_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='bathroom_time',
        ),
    ]
