# Generated by Django 2.2.6 on 2019-10-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0017_auto_20191029_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='srisk',
            field=models.BooleanField(default=False, verbose_name='Суицидальный риск'),
        ),
    ]
