# Generated by Django 2.2.6 on 2019-10-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0018_auto_20191029_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='drisk',
            field=models.BooleanField(default=False, verbose_name='Риск падения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fullname',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Госпитализирован в данный момент?'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='room',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Номер палаты'),
        ),
    ]
