# Generated by Django 2.2.6 on 2019-10-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0019_auto_20191029_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='self_harm',
            field=models.BooleanField(default=False, verbose_name='Самоповреждения'),
        ),
    ]
