# Generated by Django 2.2.6 on 2019-10-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0020_patient_self_harm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='bathroom_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
