# Generated by Django 2.2.6 on 2019-10-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0021_auto_20191029_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='suicidal_risk',
            field=models.SmallIntegerField(choices=[(0, 'Нет'), (1, 'Низкий'), (2, 'Высокий')]),
        ),
    ]
