# Generated by Django 2.2.6 on 2019-10-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0022_auto_20191029_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['-current_date']},
        ),
    ]
